--- #YAML:1.0
name:                Text-CSV-BulkData
version:             0.01
abstract:            generate csv file with bulk data
license:             ~
author:              
    - A. U. Thor <webmaster@localdomain>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
